version: '3.8'

services:
  db_yamdb:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web_yamdb:
    image: potesuch/yamdb
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
     - "8002:8000"
    depends_on:
      - db_yamdb
    env_file:
      - ./.env
  nginx_yamdb:
    image: nginx:1.25.4-alpine
    ports:
      - "82:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web_yamdb

volumes:
  static_value:
  media_value:
